within OneSatSim.Foundation.Models;
model ASRTUStateDatabase "星上状态数据库"
  OneSatSim.Foundation.Interfaces.InformationPort live;
  OneSatSim.Foundation.Interfaces.ASRTUStatePort database;
equation
  // 状态数据库是设备状态总线的确定性语义镜像。连续工程遥测镜像直接读取
  // 本接口；这里不对大型连接器记录进行事件采样或算法复制。
  database.busVoltage=live.device.busVoltage;
  database.busCurrent=live.device.busCurrent;
  database.subArrayVoltage=live.device.subArrayVoltage;
  database.mpptVoltage=live.device.mpptVoltage;
  database.mpptCurrent=live.device.mpptCurrent;
  database.chargerVoltage=live.device.chargerVoltage;
  database.chargerCurrent=live.device.chargerCurrent;
  database.pdState=live.device.pdState;
  database.tcState=live.device.tcState;
  database.pdCurrent=live.device.pdCurrent;
  database.tcCurrent=live.device.tcCurrent;
  database.thermistorTemperature=live.device.thermistorTemperature;
  database.heaterUpper=live.device.heaterUpper;
  database.heaterLower=live.device.heaterLower;
  database.wheelSpeed=live.device.wheelSpeed;
  database.wheelCurrent=live.device.wheelCurrent;
  database.wheelStatus=live.device.wheelStatus;
  database.starQuaternion=live.device.starQuaternion;
  database.starAngularVelocity=live.device.starAngularVelocity;
  database.starStatus=live.device.starStatus;
  database.yh50Rate=live.device.yh50Rate;
  database.mems=live.device.mems;
  database.magneticField=live.device.magneticField;
  database.sunAngle=live.device.sunAngle;
  database.gnssPosition=live.device.gnssPosition;
  database.gnssVelocity=live.device.gnssVelocity;
  database.gnssFix=live.device.gnssFix;
  database.cameraStatus=live.device.cameraStatus;
  database.cmosStatus=live.device.cmosStatus;
  database.ttcStatus=live.device.ttcStatus;
  database.basebandStatus=live.device.basebandStatus;
  database.bootSeconds=noEvent(integer(time));
  database.milliseconds=noEvent(integer(mod(time,1)*1000));
  database.commandErrorCount=live.device.commandErrorCount;
  database.watchdogCount=live.device.watchdogCount;
  database.cpuTemperature=live.device.cpuTemperature;
  database.boardTemperature=live.device.boardTemperature;
  database.currentCommand=live.commandStatus.currentCommand;
  database.executionStatus=live.commandStatus.executionStatus;
  database.rejectReason=live.commandStatus.rejectReason;
  database.missionMode=live.commandStatus.missionMode;
  database.controlMode=live.commandStatus.controlMode;
  database.commandId=live.commandStatus.commandId;
  database.transitionCounter=live.commandStatus.transitionCounter;
  database.commandAccepted=live.commandStatus.accepted;
  database.commandRejected=live.commandStatus.rejected;
  database.commandExecuting=live.commandStatus.executing;
  database.commandCompleted=live.commandStatus.completed;
  database.commandFailed=live.commandStatus.failed;
  database.commandAborted=live.commandStatus.aborted;
  database.commandTimeout=live.commandStatus.timeout;
  database.imagingOpportunity=live.commandStatus.imagingOpportunity;
  database.downlinkOpportunity=live.commandStatus.downlinkOpportunity;
  database.imagingAllowed=live.commandStatus.imagingAllowed;
  database.downlinkAllowed=live.commandStatus.downlinkAllowed;
  database.safeModeRequired=live.commandStatus.safeModeRequired;
  database.executionTime=live.commandStatus.executionTime;
  database.usedStorage=live.payload.storedBytes;
  database.remainingStorage=live.payload.remainingBytes;
  database.attitudeError=live.device.attitudeError;
  database.attitudeSettled=live.device.attitudeSettled;
  database.batteryVoltage=live.device.batteryVoltage;
  database.batterySOC=live.device.batterySOC;
  annotation(Icon(graphics={Rectangle(extent={{-100,70},{100,-70}},lineColor={0,80,150},fillColor={225,238,250},fillPattern=FillPattern.Solid),Ellipse(extent={{-70,48},{70,12}},fillColor={90,145,195},fillPattern=FillPattern.Solid),Rectangle(extent={{-70,30},{70,-42}},fillColor={200,222,240},fillPattern=FillPattern.Solid),Ellipse(extent={{-70,-25},{70,-60}},fillColor={90,145,195},fillPattern=FillPattern.Solid),Text(extent={{-90,-8},{90,18}},textString="STATE DB")}),Documentation(info="<html><h4>用途与保留理由</h4><p><b>系统角色：</b>把统一DeviceStatusBus连续、确定性地镜像为OBC可用状态快照接口</p><p><b>黑箱理由：</b>大量确定字段映射适合集中方程化，避免在白箱画布中产生不可读的数百条连线</p><h4>方程或算法实现</h4><p><b>实现：</b>equation区逐字段赋值，覆盖电源、热控、姿控、导航、载荷、通信、时间和板温；无connect语句</p><p><b>连续/离散特性：</b>没有独立采样时钟，数据库随设备状态连续更新；连续工程遥测镜像直接读取该接口</p><p><b>接口：</b>database（ASRTUStatePort）</p><h4>参数、状态与交互</h4><p><b>关键参数：</b>三路母线、24路PDB/TCB、32路热敏、4轮、双星敏、导航和状态字段</p><p><b>关键状态：</b>database接口中的当前OBC状态镜像</p><p><b>遥测关系：</b>位于DeviceStatusBus与ASRTUEngineeringTelemetryMirror之间，是四层变量中的OBC state层</p><p><b>使用说明：</b>该模型不含connect语句，字段映射修改后需重新执行checkModel。</p></html>"));
end ASRTUStateDatabase;
