within OneSatSim.Foundation.Models;
model MissionFeedbackAdapter "物理状态到任务反馈的选择适配器"
  OneSatSim.Foundation.Interfaces.DeviceStatusBus device annotation(Placement(transformation(extent={{-112,35},{-92,55}})));
  OneSatSim.Foundation.Interfaces.PayloadDataPort payload annotation(Placement(transformation(extent={{-112,-55},{-92,-35}})));
  OneSatSim.Foundation.Interfaces.MissionFeedbackBus feedback annotation(Placement(transformation(extent={{92,-10},{112,10}})));
protected
  Modelica.Blocks.Interfaces.RealOutput totalAvailableSolarPowerPublisher(unit="W") annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.RealOutput totalDeliveredSolarPowerPublisher(unit="W") annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.BooleanOutput aocsAvailablePublisher annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.RealOutput attitudeErrorPublisher(unit="rad") annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.BooleanOutput attitudeSettledPublisher annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.BooleanOutput imagingAttitudeReadyPublisher annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.BooleanOutput groundLinkAttitudeReadyPublisher annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.BooleanOutput attitudeEstimateValidPublisher annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.BooleanOutput wheelActuationAvailablePublisher annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.RealOutput batterySOCPublisher annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.RealOutput batteryTemperaturePublisher(unit="K") annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.RealOutput busVoltagePublisher(unit="V") annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.BooleanOutput cameraReadyPublisher annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.RealOutput capacityStoragePublisher(unit="1") annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.BooleanOutput dataAvailablePublisher annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.RealOutput downlinkReadRatePublisher(unit="1/s") annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.RealOutput generatedPowerPublisher(unit="W") annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.RealOutput loadPowerPublisher(unit="W") annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.RealOutput payloadTemperaturePublisher(unit="K") annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.RealOutput remainingStoragePublisher(unit="1") annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.BooleanOutput storageFullPublisher annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.BooleanOutput storageHighPublisher annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.RealOutput storageUtilizationPublisher annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.BooleanOutput transmitterReadyPublisher annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.RealOutput transmitterTemperaturePublisher(unit="K") annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Modelica.Blocks.Interfaces.RealOutput usedStoragePublisher(unit="1") annotation(Placement(visible=false, transformation(extent={{-4,-4},{4,4}})));
  Foundation.Interfaces.RealSignalBridge informationRealBridge[15] annotation(Placement(transformation(extent={{58,-92},{66,-84}})));
  Foundation.Interfaces.BooleanSignalBridge informationBooleanBridge[11] annotation(Placement(transformation(extent={{82,-92},{90,-84}})));
equation
  batterySOCPublisher=device.batterySOC;
  busVoltagePublisher=device.busVoltage[1];
  generatedPowerPublisher=sum(max(0,device.solarOutputPower[i]) for i in 1:3);
  totalAvailableSolarPowerPublisher=sum(max(0,device.availableSolarPower[i]) for i in 1:3);
  totalDeliveredSolarPowerPublisher=sum(max(0,device.solarOutputPower[i]) for i in 1:3);
  loadPowerPublisher=abs(device.busVoltage[1]*device.busCurrent[1]);
  batteryTemperaturePublisher=0.5*(device.thermistorTemperature[31]+device.thermistorTemperature[32]);
  payloadTemperaturePublisher=device.thermistorTemperature[30];
  transmitterTemperaturePublisher=device.transmitterTemperature;
  attitudeErrorPublisher=device.attitudeError;
  attitudeSettledPublisher=device.attitudeSettled;
  imagingAttitudeReadyPublisher=device.imagingAttitudeReady;
  groundLinkAttitudeReadyPublisher=device.groundLinkAttitudeReady;
  attitudeEstimateValidPublisher=device.starStatus[1] > 0;
  wheelActuationAvailablePublisher=device.wheelStatus[1] > 0 and device.wheelStatus[2] > 0 and
    device.wheelStatus[3] > 0 and device.wheelStatus[4] > 0;
  aocsAvailablePublisher=attitudeEstimateValidPublisher and wheelActuationAvailablePublisher;
  cameraReadyPublisher=device.cameraStatus > 0;
  transmitterReadyPublisher=device.transmitterStatus > 0;
  usedStoragePublisher=payload.storedBytes;
  capacityStoragePublisher=payload.capacityBytes;
  remainingStoragePublisher=payload.remainingBytes;
  storageUtilizationPublisher=if payload.capacityBytes > 0 then max(0,min(1,payload.storedBytes/payload.capacityBytes)) else 0;
  downlinkReadRatePublisher=payload.downlinkReadRate;
  dataAvailablePublisher=payload.dataAvailable;
  storageHighPublisher=payload.storageHigh;
  storageFullPublisher=payload.storageFull;
  connect(totalAvailableSolarPowerPublisher,informationRealBridge[1].u) annotation(Line(points={{-78,50},{-102,50}},color={0,0,127}));
  connect(informationRealBridge[1].y,device.totalAvailableSolarPower) annotation(Line(points={{-78,50},{-102,50}},color={0,0,127}));
  connect(totalDeliveredSolarPowerPublisher,informationRealBridge[2].u) annotation(Line(points={{-78,38},{-102,38}},color={0,0,127}));
  connect(informationRealBridge[2].y,device.totalDeliveredSolarPower) annotation(Line(points={{-78,38},{-102,38}},color={0,0,127}));
  connect(aocsAvailablePublisher,informationBooleanBridge[1].u) annotation(Line(points={{78,60},{102,60},{102,0}},color={255,0,255}));
  connect(informationBooleanBridge[1].y,feedback.aocsAvailable) annotation(Line(points={{78,60},{102,60},{102,0}},color={255,0,255}));
  connect(attitudeErrorPublisher,informationRealBridge[3].u) annotation(Line(points={{78,54},{102,54},{102,0}},color={0,0,127}));
  connect(informationRealBridge[3].y,feedback.attitudeError) annotation(Line(points={{78,54},{102,54},{102,0}},color={0,0,127}));
  connect(attitudeSettledPublisher,informationBooleanBridge[2].u) annotation(Line(points={{78,48},{102,48},{102,0}},color={255,0,255}));
  connect(informationBooleanBridge[2].y,feedback.attitudeSettled) annotation(Line(points={{78,48},{102,48},{102,0}},color={255,0,255}));
  connect(imagingAttitudeReadyPublisher,informationBooleanBridge[8].u) annotation(Line(points={{78,44},{82,44}},color={255,0,255}));
  connect(informationBooleanBridge[8].y,feedback.imagingAttitudeReady) annotation(Line(points={{90,44},{102,44},{102,0}},color={255,0,255}));
  connect(groundLinkAttitudeReadyPublisher,informationBooleanBridge[9].u) annotation(Line(points={{78,40},{82,40}},color={255,0,255}));
  connect(informationBooleanBridge[9].y,feedback.groundLinkAttitudeReady) annotation(Line(points={{90,40},{102,40},{102,0}},color={255,0,255}));
  connect(attitudeEstimateValidPublisher,informationBooleanBridge[10].u) annotation(Line(points={{78,36},{82,36}},color={255,0,255}));
  connect(informationBooleanBridge[10].y,feedback.attitudeEstimateValid) annotation(Line(points={{90,36},{102,36},{102,0}},color={255,0,255}));
  connect(wheelActuationAvailablePublisher,informationBooleanBridge[11].u) annotation(Line(points={{78,32},{82,32}},color={255,0,255}));
  connect(informationBooleanBridge[11].y,feedback.wheelActuationAvailable) annotation(Line(points={{90,32},{102,32},{102,0}},color={255,0,255}));
  connect(batterySOCPublisher,informationRealBridge[4].u) annotation(Line(points={{78,42},{102,42},{102,0}},color={0,0,127}));
  connect(informationRealBridge[4].y,feedback.batterySOC) annotation(Line(points={{78,42},{102,42},{102,0}},color={0,0,127}));
  connect(batteryTemperaturePublisher,informationRealBridge[5].u) annotation(Line(points={{78,36},{102,36},{102,0}},color={0,0,127}));
  connect(informationRealBridge[5].y,feedback.batteryTemperature) annotation(Line(points={{78,36},{102,36},{102,0}},color={0,0,127}));
  connect(busVoltagePublisher,informationRealBridge[6].u) annotation(Line(points={{78,30},{102,30},{102,0}},color={0,0,127}));
  connect(informationRealBridge[6].y,feedback.busVoltage) annotation(Line(points={{78,30},{102,30},{102,0}},color={0,0,127}));


  connect(cameraReadyPublisher,informationBooleanBridge[3].u) annotation(Line(points={{78,24},{102,24},{102,0}},color={255,0,255}));
  connect(informationBooleanBridge[3].y,feedback.cameraReady) annotation(Line(points={{78,24},{102,24},{102,0}},color={255,0,255}));
  connect(capacityStoragePublisher,informationRealBridge[7].u) annotation(Line(points={{78,18},{102,18},{102,0}},color={0,0,127}));
  connect(informationRealBridge[7].y,feedback.capacityStorage) annotation(Line(points={{78,18},{102,18},{102,0}},color={0,0,127}));
  connect(dataAvailablePublisher,informationBooleanBridge[4].u) annotation(Line(points={{78,12},{102,12},{102,0}},color={255,0,255}));
  connect(informationBooleanBridge[4].y,feedback.dataAvailable) annotation(Line(points={{78,12},{102,12},{102,0}},color={255,0,255}));
  connect(downlinkReadRatePublisher,informationRealBridge[8].u) annotation(Line(points={{78,6},{102,6},{102,0}},color={0,0,127}));
  connect(informationRealBridge[8].y,feedback.downlinkReadRate) annotation(Line(points={{78,6},{102,6},{102,0}},color={0,0,127}));
  connect(generatedPowerPublisher,informationRealBridge[9].u) annotation(Line(points={{78,0},{102,0},{102,0}},color={0,0,127}));
  connect(informationRealBridge[9].y,feedback.generatedPower) annotation(Line(points={{78,0},{102,0},{102,0}},color={0,0,127}));
  connect(loadPowerPublisher,informationRealBridge[10].u) annotation(Line(points={{78,-6},{102,-6},{102,0}},color={0,0,127}));
  connect(informationRealBridge[10].y,feedback.loadPower) annotation(Line(points={{78,-6},{102,-6},{102,0}},color={0,0,127}));
  connect(payloadTemperaturePublisher,informationRealBridge[11].u) annotation(Line(points={{78,-12},{102,-12},{102,0}},color={0,0,127}));
  connect(informationRealBridge[11].y,feedback.payloadTemperature) annotation(Line(points={{78,-12},{102,-12},{102,0}},color={0,0,127}));
  connect(remainingStoragePublisher,informationRealBridge[12].u) annotation(Line(points={{78,-18},{102,-18},{102,0}},color={0,0,127}));
  connect(informationRealBridge[12].y,feedback.remainingStorage) annotation(Line(points={{78,-18},{102,-18},{102,0}},color={0,0,127}));
  connect(storageFullPublisher,informationBooleanBridge[5].u) annotation(Line(points={{78,-24},{102,-24},{102,0}},color={255,0,255}));
  connect(informationBooleanBridge[5].y,feedback.storageFull) annotation(Line(points={{78,-24},{102,-24},{102,0}},color={255,0,255}));
  connect(storageHighPublisher,informationBooleanBridge[6].u) annotation(Line(points={{78,-30},{102,-30},{102,0}},color={255,0,255}));
  connect(informationBooleanBridge[6].y,feedback.storageHigh) annotation(Line(points={{78,-30},{102,-30},{102,0}},color={255,0,255}));
  connect(storageUtilizationPublisher,informationRealBridge[13].u) annotation(Line(points={{78,-36},{102,-36},{102,0}},color={0,0,127}));
  connect(informationRealBridge[13].y,feedback.storageUtilization) annotation(Line(points={{78,-36},{102,-36},{102,0}},color={0,0,127}));
  connect(transmitterReadyPublisher,informationBooleanBridge[7].u) annotation(Line(points={{78,-42},{102,-42},{102,0}},color={255,0,255}));
  connect(informationBooleanBridge[7].y,feedback.transmitterReady) annotation(Line(points={{78,-42},{102,-42},{102,0}},color={255,0,255}));
  connect(transmitterTemperaturePublisher,informationRealBridge[14].u) annotation(Line(points={{78,-48},{102,-48},{102,0}},color={0,0,127}));
  connect(informationRealBridge[14].y,feedback.transmitterTemperature) annotation(Line(points={{78,-48},{102,-48},{102,0}},color={0,0,127}));
  connect(usedStoragePublisher,informationRealBridge[15].u) annotation(Line(points={{78,-54},{102,-54},{102,0}},color={0,0,127}));
  connect(informationRealBridge[15].y,feedback.usedStorage) annotation(Line(points={{78,-54},{102,-54},{102,0}},color={0,0,127}));
  annotation(Icon(graphics={Rectangle(extent={{-100,70},{100,-70}},lineColor={20,105,125},fillColor={225,244,243},fillPattern=FillPattern.Solid),Line(points={{-72,30},{0,30},{0,-30},{72,-30}},color={20,105,125},thickness=2),Text(extent={{-94,-64},{94,-42}},textString="PHYS FEEDBACK")}),Documentation(info="<html><h4>功能定位</h4><p>从大型DeviceStatusBus和PayloadDataPort中选择任务规划、安全监视和动作时序真正需要的窄反馈。</p><h4>输入与接口关系</h4><p>device提供电源、热、姿态、通信和设备状态；payload提供存储量、容量及读写率。</p><h4>内部职责与实现</h4><p>计算总太阳可用/交付功率、姿控可用性与温度/电源/存储摘要，再经小型Bridge形成MissionFeedbackBus。</p><h4>输出</h4><p>feedback包含SOC、母线电压、关键温度、姿态误差与稳定性、相机/通信状态、存储与功率等任务判据。</p><h4>连续/离散状态</h4><p>纯代数、无采样和记忆；反馈随物理状态连续或离散更新。</p><h4>使用与观察</h4><p>由MissionControlUnit连接到Planner、SafetyMonitor和Sequencer。追溯安全或任务拒绝时查看对应摘要及原始device字段。</p><h4>建模边界</h4><p>不形成遥测包、不进行滤波估计，也不复制完整设备总线。</p></html>"));
end MissionFeedbackAdapter;
