within OneSatSim.Foundation.Interfaces;
connector ASRTUStatePort "星上状态数据库接口"
  RealSignal busVoltage[3]; RealSignal busCurrent[3]; RealSignal subArrayVoltage[3];
  RealSignal mpptVoltage[3]; RealSignal mpptCurrent[3];
  RealSignal chargerVoltage[2]; RealSignal chargerCurrent[2];
  IntegerSignal pdState[24]; IntegerSignal tcState[24];
  RealSignal pdCurrent[24]; RealSignal tcCurrent[24];
  RealSignal thermistorTemperature[32]; RealSignal heaterUpper[14]; RealSignal heaterLower[14];
  RealSignal wheelSpeed[4]; RealSignal wheelCurrent[4]; IntegerSignal wheelStatus[4];
  RealSignal starQuaternion[2,4]; RealSignal starAngularVelocity[2,3]; IntegerSignal starStatus[2];
  RealSignal yh50Rate[3]; RealSignal mems[6]; RealSignal magneticField[3]; RealSignal sunAngle[2];
  RealSignal gnssPosition[3]; RealSignal gnssVelocity[3]; IntegerSignal gnssFix;
  IntegerSignal cameraStatus; IntegerSignal cmosStatus; IntegerSignal ttcStatus; IntegerSignal basebandStatus;
  IntegerSignal bootSeconds; IntegerSignal milliseconds; IntegerSignal commandErrorCount; IntegerSignal watchdogCount;
  RealSignal batteryVoltage(unit="V"); RealSignal batterySOC;
  RealSignal cpuTemperature; RealSignal boardTemperature;
  OneSatSim.Foundation.Types.CommandType currentCommand;
  OneSatSim.Foundation.Types.CommandExecutionStatus executionStatus;
  OneSatSim.Foundation.Types.RejectReason rejectReason;
  OneSatSim.Foundation.Types.MissionMode missionMode;
  OneSatSim.Foundation.Types.ControlMode controlMode;
  IntegerSignal commandId; IntegerSignal transitionCounter;
  BooleanSignal commandAccepted; BooleanSignal commandRejected; BooleanSignal commandExecuting;
  BooleanSignal commandCompleted; BooleanSignal commandFailed; BooleanSignal commandAborted; BooleanSignal commandTimeout;
  BooleanSignal imagingOpportunity; BooleanSignal downlinkOpportunity;
  BooleanSignal imagingAllowed; BooleanSignal downlinkAllowed; BooleanSignal safeModeRequired;
  RealSignal executionTime; RealSignal usedStorage; RealSignal remainingStorage;
  RealSignal attitudeError; BooleanSignal attitudeSettled;
  annotation(Documentation(info="<html><h4>接口语义</h4><p><b>用途：</b>保存遥测采样前的OBC状态镜像，名称作为兼容性API保留</p><p><b>字段与单位：</b>母线、配电、热敏、飞轮、星敏、惯导、GNSS、载荷通信、时间计数和板温</p><p><b>信号方向语义：</b>StateDatabase提供；TelemetryScheduler与EngineeringTelemetrySampler读取</p><p><b>典型连接：</b>仅用于OnboardComputerUnit内部必要黑箱之间</p><p><b>建模注意：</b>该连接器用于Modelica无因果连接网络；字段名称表达工程语义，不能仅凭曲线数组序号判断来源。</p></html>"));
end ASRTUStatePort;
