within OneSatSim.Foundation.Interfaces;
connector CommandStatusBus "Mission command lifecycle and execution feedback"
  CommandTypeSignal currentCommand;
  CommandExecutionStatusSignal executionStatus;
  RejectReasonSignal rejectReason;
  MissionModeSignal missionMode;
  ControlModeSignal controlMode;
  IntegerSignal commandId;
  IntegerSignal transitionCounter;
  BooleanSignal accepted;
  BooleanSignal rejected;
  BooleanSignal executing;
  BooleanSignal completed;
  BooleanSignal failed;
  BooleanSignal aborted;
  BooleanSignal timeout;
  BooleanSignal safePreemption;
  RealSignal executionTime(unit="s");
  BooleanSignal imagingOpportunity;
  BooleanSignal downlinkOpportunity;
  BooleanSignal imagingAllowed;
  BooleanSignal downlinkAllowed;
  BooleanSignal safeModeRequired;
  BooleanSignal imagingCaptureStarted "当前/最近一次成像任务曾进入Capture";
  BooleanSignal imagingImageComplete "当前/最近一次成像任务形成完整图像";
  RealSignal imagingValidImageBytes(unit="1") "当前/最近一次成像有效字节数";
  RejectReasonSignal imagingFailureReason "当前/最近一次成像持久化终止原因";
  annotation(Icon(graphics={Rectangle(extent={{-100,60},{100,-60}},lineColor={155,85,20},fillColor={250,240,220},fillPattern=FillPattern.Solid),Text(extent={{-92,22},{92,-18}},textString="CMD STATUS")}),Documentation(info="<html><p>提供任务指令从请求、接受/拒绝、执行、完成、失败到安全抢占的可遥测反馈。成像KPI明确区分进入Capture、完整图像、部分有效字节和持久化失败原因，不再用单一“成功”计数混淆生命周期。</p></html>"));
end CommandStatusBus;
