within OneSatSim.Foundation.Interfaces;
connector MissionControlBus "Internal OBC mission-control coordination bus"
  BooleanSignal imagingOpportunity;
  BooleanSignal downlinkOpportunity;
  BooleanSignal targetPrePointOpportunity "Preparation opportunity before formal imaging visibility";
  BooleanSignal earlyTargetPrePointOpportunity "Early target pre-slew opportunity";
  BooleanSignal groundPrePointOpportunity "Preparation opportunity before formal ground contact";
  IntegerSignal targetPrePointIndex;
  IntegerSignal earlyTargetPrePointIndex;
  IntegerSignal groundPrePointIndex;
  IntegerSignal targetWindowId "Identity of the current target preparation window";
  IntegerSignal groundWindowId "Identity of the current ground preparation window";
  BooleanSignal eclipse;
  BooleanSignal sunlightAvailable;
  BooleanSignal groundContact;
  BooleanSignal targetVisible;
  IntegerSignal groundStationIndex;
  IntegerSignal targetIndex;
  BooleanSignal requestValid;
  OneSatSim.Foundation.Types.CommandType requestedCommand;
  IntegerSignal requestedTargetIndex;
  IntegerSignal requestedGroundStationIndex;
  IntegerSignal requestWindowId;
  IntegerSignal requestId;
  BooleanSignal requestPending "A request that has not yet been handled by the arbiter";
  BooleanSignal spacecraftHealthy;
  BooleanSignal imagingAllowed;
  BooleanSignal downlinkAllowed;
  BooleanSignal powerHealthy;
  BooleanSignal thermalHealthy;
  BooleanSignal attitudeHealthy;
  BooleanSignal storageHealthy;
  BooleanSignal safeModeRequired;
  BooleanSignal recoveryAllowed;
  OneSatSim.Foundation.Types.RejectReason safetyReason;
  BooleanSignal arbiterAccepted;
  BooleanSignal arbiterRejected;
  OneSatSim.Foundation.Types.CommandType acceptedCommand;
  IntegerSignal acceptedCommandId;
  OneSatSim.Foundation.Types.RejectReason rejectReason;
  OneSatSim.Foundation.Types.MissionMode missionMode;
  OneSatSim.Foundation.Types.ControlMode controlMode;
  OneSatSim.Foundation.Types.CommandType currentCommand;
  IntegerSignal activeRequestId;
  IntegerSignal activeTargetIndex;
  IntegerSignal activeGroundStationIndex;
  BooleanSignal activeTargetVisible;
  BooleanSignal activeTargetPreparationOpportunity;
  BooleanSignal activeTargetEarlyPrePointOpportunity;
  BooleanSignal activeGroundContact;
  RealSignal targetElevationRate(unit="1/s");
  RealSignal groundElevationRate(unit="1/s");
  BooleanSignal targetElevationIncreasing;
  BooleanSignal groundElevationIncreasing;
  RealSignal offNadirAngle(unit="rad");
  RealSignal cameraLookAngle(unit="rad");
  RealSignal targetSunElevation(unit="rad");
  BooleanSignal offNadirValid;
  BooleanSignal cameraFOVValid;
  BooleanSignal targetIlluminationValid;
  BooleanSignal imagingValid;
  RealSignal storageUtilization "Stored bytes divided by operational buffer capacity";
  BooleanSignal storageDrainMode "50/20 percent hysteresis latch";
  OneSatSim.Foundation.Types.CommandExecutionStatus executionStatus;
  IntegerSignal transitionCounter;
  RealSignal stateElapsed(unit="s");
  RealSignal executionTime(unit="s");
  BooleanSignal commandExecuting;
  BooleanSignal commandCompleted;
  BooleanSignal commandFailed;
  BooleanSignal commandAborted;
  BooleanSignal commandTimeout;
  OneSatSim.Foundation.Types.ImagingPhase imagingPhase;
  BooleanSignal payloadPowerCommand;
  BooleanSignal captureCommand;
  BooleanSignal imagingBusy;
  BooleanSignal imagingActive;
  BooleanSignal imagingCompleted;
  BooleanSignal imagingFailed;
  BooleanSignal imagingAborted;
  BooleanSignal imagingTimeout;
  OneSatSim.Foundation.Types.RejectReason imagingFailureReason;
  OneSatSim.Foundation.Types.DownlinkPhase downlinkPhase;
  BooleanSignal communicationPowerCommand;
  BooleanSignal transmitCommand;
  BooleanSignal downlinkBusy;
  BooleanSignal downlinkActive;
  BooleanSignal downlinkCompleted;
  BooleanSignal downlinkFailed;
  BooleanSignal downlinkAborted;
  BooleanSignal downlinkTimeout;
  BooleanSignal safeEntryComplete;
  BooleanSignal recoveryReady;
  BooleanSignal recoveryComplete;
  annotation(Icon(graphics={Rectangle(extent={{-100,60},{100,-60}},lineColor={105,65,145},fillColor={241,235,248},fillPattern=FillPattern.Solid),Text(extent={{-92,22},{92,-18}},textString="MISSION CTRL")}),Documentation(info="<html><p>OBC内部任务控制协调总线。机会、请求、安全许可、仲裁结果、任务状态和动作序列字段分别由唯一控制核心提供；它不替代设备InformationPort。</p></html>"));
end MissionControlBus;
