within OneSatSim.Foundation.Calculations;
model BodyMountedSolarArrayPlusYCalculation "+Y双串体装太阳电池阵性能计算"
  parameter Modelica.Units.SI.Area activeArea=0.069156;
  parameter Real cellEfficiency(min=0,max=1)=0.32;
  parameter Real solarLifeFactor(min=0,max=1)=1;
  parameter Real etaMPPT(min=0,max=1)=0.95;
  parameter Real solarAbsorptivity(min=0,max=1)=0.90 "电池覆盖区太阳/反照吸收率等效值";
  parameter Real infraredAbsorptivity(min=0,max=1)=0.85 "电池覆盖区地球红外吸收率等效值";
  parameter Real panelNormalBody[3]={0,1,0};
  Modelica.Blocks.Interfaces.RealInput sunVectorBody[3] annotation(Placement(transformation(extent={{-120,65},{-80,85}})));
  Modelica.Blocks.Interfaces.RealInput solarFlux(unit="W/m2") annotation(Placement(transformation(extent={{-120,35},{-80,55}})));
  Modelica.Blocks.Interfaces.RealInput earthVectorBody[3] annotation(Placement(transformation(extent={{-120,20},{-80,40}})));
  Modelica.Blocks.Interfaces.RealInput albedoFlux(unit="W/m2") annotation(Placement(transformation(extent={{-120,5},{-80,25}})));
  Modelica.Blocks.Interfaces.RealInput earthInfraredFlux(unit="W/m2") annotation(Placement(transformation(extent={{-120,-10},{-80,10}})));
  Modelica.Blocks.Interfaces.RealInput curtailment annotation(Placement(transformation(extent={{-120,-25},{-80,-5}})));
  Modelica.Blocks.Interfaces.RealInput rawSourceVoltage(unit="V") annotation(Placement(transformation(extent={{-120,-25},{-80,-5}})));
  Modelica.Blocks.Interfaces.RealInput measuredTerminalVoltage(unit="V") annotation(Placement(transformation(extent={{-120,-55},{-80,-35}})));
  Modelica.Blocks.Interfaces.RealInput measuredTerminalCurrent(unit="A") annotation(Placement(transformation(extent={{-120,-85},{-80,-65}})));
  Modelica.Blocks.Interfaces.RealOutput sourceCurrentCommand(unit="A") annotation(Placement(transformation(extent={{80,70},{100,90}})));
  Modelica.Blocks.Interfaces.RealOutput incidenceCos annotation(Placement(transformation(extent={{80,50},{100,70}})));
  Modelica.Blocks.Interfaces.RealOutput availablePower(unit="W") annotation(Placement(transformation(extent={{80,30},{100,50}})));
  Modelica.Blocks.Interfaces.RealOutput deliveredPower(unit="W") annotation(Placement(transformation(extent={{80,10},{100,30}})));
  Modelica.Blocks.Interfaces.RealOutput absorbedHeat(unit="W") annotation(Placement(transformation(extent={{80,-10},{100,10}})));
  Modelica.Blocks.Interfaces.RealOutput subArrayVoltage(unit="V") annotation(Placement(transformation(extent={{80,-30},{100,-10}})));
  Modelica.Blocks.Interfaces.RealOutput mpptOperatingVoltage(unit="V") annotation(Placement(transformation(extent={{80,-50},{100,-30}})));
  Modelica.Blocks.Interfaces.RealOutput mpptTelemetryCurrent(unit="A") annotation(Placement(transformation(extent={{80,-70},{100,-50}})));
protected
  Real mpptPowerCommand(unit="W") annotation(HideResult=true);
  Real stringCurrentA(unit="A") annotation(HideResult=true);
  Real stringCurrentB(unit="A") annotation(HideResult=true);
  Real cellElectricalPower(unit="W");
  Real directSolarHeat(unit="W");
  Real albedoHeat(unit="W");
  Real earthIRHeat(unit="W");
  Real mpptLossHeat(unit="W");
  Real earthIncidenceCos;
equation
  incidenceCos=max(0,min(1,panelNormalBody*sunVectorBody));
  availablePower=solarLifeFactor*activeArea*cellEfficiency*solarFlux*incidenceCos;
  cellElectricalPower=availablePower*max(0,min(1,curtailment));
  mpptPowerCommand=etaMPPT*cellElectricalPower;
  stringCurrentA=0.5*mpptPowerCommand/max(10,rawSourceVoltage);
  stringCurrentB=0.5*mpptPowerCommand/max(10,rawSourceVoltage);
  sourceCurrentCommand=stringCurrentA+stringCurrentB;
  deliveredPower=max(0,measuredTerminalVoltage*measuredTerminalCurrent);
  earthIncidenceCos=max(0,min(1,panelNormalBody*earthVectorBody));
  directSolarHeat=max(0,solarAbsorptivity*activeArea*solarFlux*incidenceCos-cellElectricalPower);
  albedoHeat=solarAbsorptivity*activeArea*albedoFlux*earthIncidenceCos;
  earthIRHeat=infraredAbsorptivity*activeArea*earthInfraredFlux*earthIncidenceCos;
  mpptLossHeat=max(0,cellElectricalPower-mpptPowerCommand);
  absorbedHeat=directSolarHeat+albedoHeat+earthIRHeat+mpptLossHeat;
  subArrayVoltage=if solarFlux > 1 and incidenceCos > 1e-6 then 5.5*(0.90+0.10*incidenceCos) else 0;
  mpptOperatingVoltage=if solarFlux > 1 and incidenceCos > 1e-6 then 3.445*(1+0.002*tanh(incidenceCos)) else 0;
  mpptTelemetryCurrent=if mpptOperatingVoltage > 0.1 then deliveredPower/mpptOperatingVoltage else 0;
  annotation(Icon(graphics={Rectangle(extent={{-100,72},{100,-72}},lineColor={30,70,130},fillColor={224,235,250},fillPattern=FillPattern.Solid),Line(points={{-70,0},{65,0}},color={30,70,130},arrow={Arrow.None,Arrow.Filled}),Text(extent={{-90,55},{90,20}},textString="+Y PV CALC"),Text(extent={{-90,-20},{90,-52}},textString="2 STRINGS")}),Documentation(info="<html><h4>功能定位</h4><p>计算+Y双串体装太阳电池阵的入射、功率、电流、吸收热流及第二路MPPT工程量。</p><h4>输入与物理含义</h4><p>输入与+X计算相同，但panelNormalBody为+Y，且参数属于本面独立配置。</p><h4>输出与物理含义</h4><p>输出汇总两串电流并提供源电流命令、可用/交付功率、吸收热流、子阵电压和MPPT工作点。</p><h4>主要计算关系</h4><p>总受控功率先平均分配到stringCurrentA/B，再在源端求和；这样保留双串工程语义而不增加开关或电化学状态。其余功率与热流关系采用面积效率模型。</p><h4>状态、事件与假设</h4><p>纯代数、无状态；两串默认对称，不模拟串间失配、旁路二极管与局部故障。stringCurrentA/B是受保护中间量。</p><h4>调用与结果使用</h4><p>由BodyMountedSolarArrayPlusYUnit调用。主要观察汇总电流、availablePower和第二路MPPT量；只有诊断双串分配时才查看受保护中间量。</p></html>"));
end BodyMountedSolarArrayPlusYCalculation;
