within NISSA_12UCubeSat.Foundation.Calculations;
model BodyMountedSolarArrayMinusXCalculation "-X体装太阳电池阵性能计算"
  parameter Modelica.Units.SI.Area activeArea=0.062240;
  parameter Real cellEfficiency(min=0,max=1)=0.32;
  parameter Real solarLifeFactor(min=0,max=1)=1;
  parameter Real etaMPPT(min=0,max=1)=0.96;
  parameter Real solarAbsorptivity(min=0,max=1)=0.90 "电池覆盖区太阳/反照吸收率等效值";
  parameter Real infraredAbsorptivity(min=0,max=1)=0.85 "电池覆盖区地球红外吸收率等效值";
  parameter Real panelNormalBody[3]={-1,0,0};
  Modelica.Blocks.Interfaces.RealInput sunVectorBody[3] annotation(Placement(transformation(extent={{-120,65},{-80,85}})));
  Modelica.Blocks.Interfaces.RealInput solarFlux(unit="W/m2") annotation(Placement(transformation(extent={{-120,35},{-80,55}})));
  Modelica.Blocks.Interfaces.RealInput earthVectorBody[3] annotation(Placement(transformation(extent={{-120,20},{-80,40}})));
  Modelica.Blocks.Interfaces.RealInput albedoFlux(unit="W/m2") annotation(Placement(transformation(extent={{-120,5},{-80,25}})));
  Modelica.Blocks.Interfaces.RealInput earthInfraredFlux(unit="W/m2") annotation(Placement(transformation(extent={{-120,-10},{-80,10}})));
  Modelica.Blocks.Interfaces.RealInput curtailment annotation(Placement(transformation(extent={{-120,-25},{-80,-5}})));
  Modelica.Blocks.Interfaces.RealInput rawSourceVoltage(unit="V") annotation(Placement(transformation(extent={{-120,-25},{-80,-5}})));
  Modelica.Blocks.Interfaces.RealInput measuredTerminalVoltage(unit="V") annotation(Placement(transformation(extent={{-120,-55},{-80,-35}})));
  Modelica.Blocks.Interfaces.RealInput measuredTerminalCurrent(unit="A") annotation(Placement(transformation(extent={{-120,-85},{-80,-65}})));
  Modelica.Blocks.Interfaces.RealOutput sourceCurrentCommand(unit="A") annotation(Placement(transformation(extent={{80,70},{100,90}})));
  Modelica.Blocks.Interfaces.RealOutput incidenceCos annotation(Placement(transformation(extent={{80,50},{100,70}})));
  Modelica.Blocks.Interfaces.RealOutput availablePower(unit="W") annotation(Placement(transformation(extent={{80,30},{100,50}})));
  Modelica.Blocks.Interfaces.RealOutput deliveredPower(unit="W") annotation(Placement(transformation(extent={{80,10},{100,30}})));
  Modelica.Blocks.Interfaces.RealOutput absorbedHeat(unit="W") annotation(Placement(transformation(extent={{80,-10},{100,10}})));
  Modelica.Blocks.Interfaces.RealOutput subArrayVoltage(unit="V") annotation(Placement(transformation(extent={{80,-30},{100,-10}})));
  Modelica.Blocks.Interfaces.RealOutput mpptOperatingVoltage(unit="V") annotation(Placement(transformation(extent={{80,-50},{100,-30}})));
  Modelica.Blocks.Interfaces.RealOutput mpptTelemetryCurrent(unit="A") annotation(Placement(transformation(extent={{80,-70},{100,-50}})));
protected
  Real mpptPowerCommand(unit="W") annotation(HideResult=true);
  Real cellElectricalPower(unit="W");
  Real directSolarHeat(unit="W");
  Real albedoHeat(unit="W");
  Real earthIRHeat(unit="W");
  Real mpptLossHeat(unit="W");
  Real earthIncidenceCos;
equation
  incidenceCos=max(0,min(1,panelNormalBody*sunVectorBody));
  availablePower=solarLifeFactor*activeArea*cellEfficiency*solarFlux*incidenceCos;
  cellElectricalPower=availablePower*max(0,min(1,curtailment));
  mpptPowerCommand=etaMPPT*cellElectricalPower;
  sourceCurrentCommand=mpptPowerCommand/max(10,rawSourceVoltage);
  deliveredPower=max(0,measuredTerminalVoltage*measuredTerminalCurrent);
  earthIncidenceCos=max(0,min(1,panelNormalBody*earthVectorBody));
  directSolarHeat=max(0,solarAbsorptivity*activeArea*solarFlux*incidenceCos-cellElectricalPower);
  albedoHeat=solarAbsorptivity*activeArea*albedoFlux*earthIncidenceCos;
  earthIRHeat=infraredAbsorptivity*activeArea*earthInfraredFlux*earthIncidenceCos;
  mpptLossHeat=max(0,cellElectricalPower-mpptPowerCommand);
  absorbedHeat=directSolarHeat+albedoHeat+earthIRHeat+mpptLossHeat;
  subArrayVoltage=if solarFlux > 1 and incidenceCos > 1e-6 then 5.1*(0.90+0.10*incidenceCos) else 0;
  mpptOperatingVoltage=if solarFlux > 1 and incidenceCos > 1e-6 then 3.25*(1+0.002*tanh(incidenceCos)) else 0;
  mpptTelemetryCurrent=if mpptOperatingVoltage > 0.1 then deliveredPower/mpptOperatingVoltage else 0;
  annotation(Icon(graphics={Rectangle(extent={{-100,72},{100,-72}},lineColor={30,70,130},fillColor={224,235,250},fillPattern=FillPattern.Solid),Line(points={{-70,0},{65,0}},color={30,70,130},arrow={Arrow.None,Arrow.Filled}),Text(extent={{-90,55},{90,20}},textString="-X PV CALC"),Text(extent={{-90,-20},{90,-52}},textString="P / I / HEAT")}),Documentation(info="<html><h4>功能定位</h4><p>计算-X体装太阳电池阵的入射、功率、电流、吸收热流及第三路MPPT工程量。</p><h4>输入与物理含义</h4><p>sunVectorBody、solarFlux、curtailment、rawSourceVoltage和端口实测电压电流分别代表环境、PCDU约束与物理支路反馈；本面法向为-X。</p><h4>输出与物理含义</h4><p>输出源电流命令、入射余弦、可用/交付功率、吸收热流、子阵电压、MPPT电压与电流。</p><h4>主要计算关系</h4><p>按-X方向余弦计算日照，面积与效率得到可用功率，MPPT效率及curtailment得到源端功率；实测交付功率由端电压和端电流乘积形成。</p><h4>状态、事件与假设</h4><p>纯代数、无状态；不包含面板热容、T14热敏、线束及开关级MPPT，这些由父白箱或建模边界处理。</p><h4>调用与结果使用</h4><p>由BodyMountedSolarArrayMinusXUnit调用。重点查看incidenceCos、availablePower、deliveredPower和第三路MPPT输出，并与T14温度在父组件中联合解释。</p></html>"));
end BodyMountedSolarArrayMinusXCalculation;
